version: "3.7"

volumes:
  postgres-data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8800
    volumes:
      - .:/usr/src/shopProject
    ports:
      - "8800:8800"
    env_file: .env
    depends_on:
      - db
    restart: always