# Generated by Django 3.1.7 on 2021-03-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210326_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.DeleteModel(
            name='CartProd',
        ),
    ]
